export const popularClothes = [
  {
    id: 1,
    price: 20,
    hasDiscount: true,
    discountPrice: 10,
    image: 'https://images.ua.prom.st/1613904815_kofta-zhenskaya-ukorochenaya.jpg',
    title: 'Woman blouse 1',
    description: 'So perhaps, you\'ve generated some fancy text, and you\'re content that you',
  },
  {
    id: 2,
    price: 15,
    hasDiscount: false,
    discountPrice: null,
    image: 'https://cdn-images.farfetch-contents.com/13/59/25/59/13592559_16356720_600.jpg',
    title: 'Woman blouse 2',
    description: 'Well, the answer is actually no',
  },
  {
    id: 3,
    price: 30,
    hasDiscount: true,
    discountPrice: 20,
    image: 'https://img.klubok.com/img/used/2018/03/07/16500/16500663_2.jpg',
    title: 'Man 1',
    description: 'haracters that you see on your electronic dev',
  },
  {
    id: 4,
    price: 45,
    hasDiscount: false,
    discountPrice: null,
    image: 'https://saks85.com/image/cache/catalog/products/1922958-LCS/1922958-LCS%D0%B5%D0%B2-286x430.jpg',
    title: 'Man 2',
    description: 'standard which creates the specification for thousands of different symbols and characters. ',
  },
  {
    id: 5,
    price: 10,
    hasDiscount: false,
    discountPrice: null,
    image: 'https://sc02.alicdn.com/kf/UTB8stqygHnJXKJkSahGq6xhzFXaA.jpg_350x350.jpg',
    title: 'Man 3',
    description: 'ongst the hundreds of thousands of symbols which are in the unicode text specifications are certain characters which resemble, or are variations of the alphabet and other keyword symbols. For example, if we can take the phrase "thug life" and convert its characters into the fancy letters ',
  },
  {
    id: 6,
    price: 25,
    hasDiscount: true,
    discountPrice: 10,
    image: 'https://ae01.alicdn.com/kf/H3713159d9f3745a5a2c89e31847d757dv/Foxmertor-100-Cotton-Shirt-High-Quality-Women-Blouse-Autumn-Long-Sleeve-Solid-White-Shirts-Slim-Female.jpg',
    title: 'Woman blouse 3',
    description: 'to create a fancy text translator, it\'s just a matter of finding these sets of letters and symbols, and linking them to their normal alphabetical equivalents.',
  },
];
